name: Push Branch
run-name: ${{github.actor}} made a ${{github.event_name}} for the branch ${{github.ref_name}}

on: [ workflow_dispatch,push ]

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    name: Docker Image Creation
    uses: ./.github/workflows/build-docker-image.yml
    with:
      tag: ${{github.ref_name}}

  install-libraries:
    name: Library Caching
    needs: build-image
    uses: ./.github/workflows/cache-libraries.yml
    with:
      image-tag: ${{github.ref_name}}

  check-security:
    name: Check Composer Security
    runs-on: ubuntu-latest
    needs: install-libraries
    container: ${{vars.REGISTRY}}/${{vars.REPOSITORY}}:${{github.ref_name}}

    steps:
      - name: Checkout to check library security
        uses: actions/checkout@v4

      - name: Get cached Composer libraries
        uses: actions/cache@v4
        with:
          key: cache-${{vars.PROJECT}}-composer-${{hashFiles('composer.lock')}}
          path: vendor

      - name: Check Composer library security
        run: composer audit

  check-quality:
    name: Check Quality
    runs-on: ubuntu-latest
    needs: install-libraries
    container: shinsenter/symfony
    continue-on-error: true

    steps:
      - name: Checkout to find changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Determine if app folder have changed
        id: folder-change
        run: |
          if git diff --name-only ${{github.event.before}} --diff-filter=ACMRTUXB; then
            echo "folder-changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Get cached Composer libraries
        uses: actions/cache@v4
        if: ${{steps.folder-change.outputs.folder-changed == 'true'}}
        with:
          key: cache-${{vars.PROJECT}}-composer-${{hashFiles('composer.lock')}}
          path: vendor

      - name: Check code quality
        if: ${{steps.folder-change.outputs.folder-changed == 'true'}}
        run: php -dmemory_limit=-1 vendor/bin/phpstan analyze $(git diff --name-only ${{github.event.before}} --diff-filter=ACMRTUXB -- '*.php')

  install-environment:
    name: CI Test Environment Installation
    needs: install-libraries
    uses: ./.github/workflows/install-environment.yml
    with:
      branch: ${{github.ref_name}}

  test-unit:
    name: Unit Test Suite
    needs: install-environment
    uses: ./.github/workflows/test-suite.yml
    with:
      suite-name: Unit
      branch: ${{github.ref_name}}
      image-tag: ${{github.ref_name}}

  test-feature:
    name: Integration Test Suite
    needs: install-environment
    uses: ./.github/workflows/test-suite.yml
    with:
      suite-name: Integration
      branch: ${{github.ref_name}}
      image-tag: ${{github.ref_name}}