name: Test Selected Suite
run-name: ${{github.actor}} tests Suite ${{inputs.suite-name}}

on:
  workflow_call:
    inputs:
      suite-name:
        type: string
        required: true
      image-tag:
        type: string
        required: true
      branch:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      suite-name:
        type: string
        required: true
        description: Suite name to test
      branch:
        type: string
        required: true
        description: Branch name

jobs:
  test-suite:
    name: ${{inputs.suite-name}} Suite Tests
    runs-on: ubuntu-latest
    container: ${{vars.REGISTRY}}/${{vars.REPOSITORY}}:${{inputs.image-tag}}

    steps:
      - name: Checkout to test
        uses: actions/checkout@v4

      - name: Get cached Composer libraries
        uses: actions/cache@v4
        with:
          key: cache-${{vars.PROJECT}}-composer-${{hashFiles('composer.lock')}}
          path: vendor

      - name: Download artifact with file and folder
        uses: actions/download-artifact@v4
        with:
          name: default-environment-${{vars.PROJECT}}-${{inputs.branch}}

      - name: Run tests
        run: php vendor/bin/phpunit --testsuite="${{inputs.suite-name}}"